### PR TITLE
Enhance TimberPhoton

### PR DESCRIPTION
**Pull request by zcuric**
This PR
- [x] implements all other available Photon filters. See: https://developer.wordpress.com/docs/photon/api
- [x] cleans up and refactors `TimberPhoton` class
- [x] reorganizes plugin structure by introducing dedicate starter php file
- [x] Changes plugin name to `Timber Jetpack Photon Image Extension` and updates `README.md`

I wanted to contribute to this plugin because I find it very useful. I will probably work on this PR a bit more  to improve the code, add some tests etc. 

Code review is appreciated!

### CODE REVIEW

**Comment by slimndap** [comment]
Hi! And thanks!

I was just wondering: what happens when you use the 'fit' function and then decide to not use the TimberPhoton plugin?

I think this is something I would run into when I switch between a dev environment (where Photon is off) and my staging environment (where Photon is on).

**Comment by zcuric** [comment]
@slimndap  You would probably run into an `exception` - missing function/filter or something. But the case is, why would anyone use these functions if you don't want use the plugin in the first place? 

Probably, use case is, if you use Photon and Timber, you'll use the filters provided by plugin. 

Maybe add more notes into documentation. What do you think?

**Comment by slimndap** [comment]
Yes, I think we should divide them in two groups:

1. Functions that are natively supported by Timber (resize, letterbox).
1. All other functions. 

Maybe we should also make it possible to turn all other functions off. I think my example of a dev site that can't run Photon is valid. If you can switch these functions off then you can still develop and test your website locally. You just can't see the Photon modifications.

**Comment by zcuric** [comment]
Ok, we can introduce some kind of protection and fallback for staging and dev environments. I'll have to think about it. Need to look at Timber image filters a bit better, though. 

If you already have an idea how can we tackle this, please make an PR. :) Thanks!

**Comment by zcuric** [comment]
Btw, I was testing this on dev environment with Photon off. On my productions server I use Photon and to test the images on dev I had to change in the database in `wp_options` table upload_image_path to the Photon type and that's how it worked.

**Pull request closed without merging**
